# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb54b688db581a8f009decbd56df75e41fac9bf1b03b0ccfc3602dd73d599e402fed6c6db9318c3caf18b04d318cab1f06804c541dd0a0c06202611ecce432e

test:
  secret_key_base: f7fe53fdeb3d6059661f5b2b789e3d7ba51d861e8d0f99dc4b4b4fda3f3ee81824e50040856534bcb888720ea113234621bb4136bc394c70cab18152bffe80c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
